$files = Get-ChildItem -Path 'c:\Users\p\Medoc\src' -Recurse -Include '*.tsx','*.ts','*.css'
foreach ($f in $files) {
    $c = Get-Content $f.FullName -Raw -Encoding UTF8
    $c = $c -replace 'bg-blue-50','bg-green-50'
    $c = $c -replace 'bg-blue-100','bg-green-100'
    $c = $c -replace 'bg-blue-500','bg-green-500'
    $c = $c -replace 'bg-blue-600','bg-green-600'
    $c = $c -replace 'bg-blue-700','bg-green-700'
    $c = $c -replace 'text-blue-100','text-green-100'
    $c = $c -replace 'text-blue-400','text-green-400'
    $c = $c -replace 'text-blue-500','text-green-500'
    $c = $c -replace 'text-blue-600','text-green-600'
    $c = $c -replace 'text-blue-700','text-green-700'
    $c = $c -replace 'border-blue-100','border-green-100'
    $c = $c -replace 'border-blue-200','border-green-200'
    $c = $c -replace 'border-blue-500','border-green-500'
    $c = $c -replace 'shadow-blue-200','shadow-green-200'
    $c = $c -replace 'shadow-blue-500','shadow-green-500'
    $c = $c -replace 'from-blue-400','from-green-400'
    $c = $c -replace 'ring-blue-600','ring-green-600'
    $c = $c -replace 'hover:bg-blue-100','hover:bg-green-100'
    $c = $c -replace 'hover:bg-blue-500','hover:bg-green-500'
    $c = $c -replace 'hover:bg-blue-700','hover:bg-green-700'
    $c = $c -replace 'hover:text-blue-700','hover:text-green-700'
    $c = $c -replace 'focus:ring-blue-600','focus:ring-green-600'
    $c = $c -replace 'shadow-blue-500/20','shadow-green-500/20'
    $c = $c -replace 'blue-500/5','green-500/5'
    $c = $c -replace 'blue-500/10','green-500/10'
    $c = $c -replace 'blue-500/20','green-500/20'
    $c = $c -replace 'from-blue-50','from-green-50'
    $c = $c -replace 'to-indigo-50','to-green-50'
    Set-Content $f.FullName $c -Encoding UTF8 -NoNewline
}
Write-Host "Done! All blue colors replaced with green."
